### ISSUE TITLE
error 500 on methodes page

### ISSUE THREAD

**Issue by SMEWebify** [SMEWebify/WebErpMesv2#238]
` production.ERROR: Trying to access array offset on value of type null {"view":{"view":"/Users/jeong-gwang-il/Downloads/SREAL/WebErpMesv2/resources/views/methods/methods-index.blade.php","data":{"errors":`

**Comment by SMEWebify** [comment]
@darrelljung111 I cannot recreate the error, have you entered data on the methods?

**Comment by darrelljung111** [comment]
As you put on manual, I followed below instead of php artisan db:seed

php artisan db:seed --class=PermissionTableSeeder
php artisan db:seed --class=CreateAdminUserSeeder

Now I don't have 500 ERROR on Dashboard or Methods. I appreciate your fast fix the issue!! 
I will test more and will let you know more if I found out the problem. 

Thank you so much!!!

**Comment by SMEWebify** [comment]
Cool, Listening to you, thank you for your interest
