### ISSUE TITLE
[STOCK] [2023-11-16 23:21:36] production.ERROR: Undefined variable $__empty_2 

### ISSUE THREAD

**Issue by SMEWebify** [SMEWebify/WebErpMesv2#243]
[2023-11-16 23:21:36] production.ERROR: Undefined variable $__empty_2 {"view":{"view":"/Users/jeong-gwang-il/Downloads/SREAL/WEBE/WebErpMesv2/resources/views/products/stocks-index.blade.php","data":{"errors":"<pre class=sf-dump id=sf-dump-1369283363 data-indent-pad=\"  \"><span class=sf-dump-note>Illuminate\\Support\\ViewErrorBag</span> {<a class=sf-dump-ref>#1713</a><samp data-depth=1 class=sf-dump-expanded>
  #<span class=sf-dump-protected title=\"Protected property\">bags</span>: []
</samp>}

**Comment by SMEWebify** [comment]
obviously this poses problems if there is no rental stock

```php
@forelse ($StockLocationList as $StockLocation)
                                <option value="{{ $StockLocation->id }}">Stock : {{ $StockLocation->Stocks->code }}| Location : {{ $StockLocation->code }} </option>
                                @endforeach
```

**Comment by SMEWebify** [comment]
add `@emtpy` and translation key

**Comment by darrelljung111** [comment]
Hi Kevin,

It is amazing!! Really thank you so much for your fixing these issue. I will test it soon. 
My company is so small manufactory working only 2 person  so I cannot donate money yet but I wanna help this project if I can help.

I will try to use WebErpMesv2 as operate my small fab so I will ask more help if there is problem. 
Everything is working well then, I will try to earn money and help this project.

I worked for Samsung, LG, US company, Japan game company and German software company as a various software engineer for 30 years. I am a only beginner as web developer but have a software skill and good network in Korea, German, US, Please always suggest if there is anything I can help. 

Thanks!

**Comment by SMEWebify** [comment]
@darrelljung111 You're welcome, thank you for your time and the feedback.  If you need help do not hesitate it will be useful for other people or ideas this present to you let's discuss between us.

**Comment by darrelljung111** [comment]
VAT and your company input problem is solved.

But, I don't know how to solve Stock 500 error issue in stocks-index.blade.php.
Would you explain in detail how I can delete 500 error in Stock?

**Comment by SMEWebify** [comment]
Hi @darrelljung111  this change doesn't passe the 500 error issue ? (red line in right side)

![image](https://github.com/SMEWebify/WebErpMesv2/assets/75578469/14792534-261c-4e12-81a7-8073cd2bca46)

**Comment by darrelljung111** [comment]
Hi!

500 Error is fixed after I input right side properly. Thank you so much!!

I have a question about logs. Usually, log display the file and line which the error is occurred. But I cannot see the line detail on Laravel.log. How I can unerstand which line is problem?

I cannot find which line is problem with below log. 
This is log when I didn't change endforelse instead of endforeach. 

[2023-11-20 23:48:37] production.ERROR: syntax error, unexpected token "endforeach", expecting "elseif" or "else" or "endif" {"view":{"view":"/Users/jeong-gwang-il/Downloads/SREAL/WEBE/WebErpMesv2/resources/views/products/stocks-index.blade.php","data":{"errors":"<pre class=sf-dump id=sf-dump-1836544160 data-indent-pad=\"  \"><span class=sf-dump-note>Illuminate\\Support\\ViewErrorBag</span> {<a class=sf-dump-ref>#1713</a><samp data-depth=1 class=sf-dump-expanded>
  #<span class=sf-dump-protected title=\"Protected property\">bags</span>: []
</samp>}
</pre><script>Sfdump(\"sf-dump-1836544160\", {\"maxDepth\":3,\"maxStringLength\":160})</script>
","stocks":"<pre class=sf-dump id=sf-dump-1434240187 data-indent-pad=\"  \"><span class=sf-dump-note>Illuminate\\Database\\Eloquent\\Collection</span> {<a class=sf-dump-ref>#1751</a><samp data-depth=1 class=sf-dump-expanded>
  #<span class=sf-dump-protected title=\"Protected property\">items</span>: []
  #<span class=sf-dump-protected title=\"Protected property\">escapeWhenCastingToString</span>: <span class=sf-dump-const>false</span>
</samp>}

**Comment by SMEWebify** [comment]
Hi @darrelljung111 

your if condition, or for loop is not closed, so it cannot finish executing the file, something is not logical.

Can you attach your file?

Or use mine:
https://github.com/SMEWebify/WebErpMesv2/blob/WEM-2.0/resources/views/products/stocks-index.blade.php
